name: docker image ci for anonymizer

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build & Push Image
        run: |
          echo "$Anonymizer" | docker login ghcr.io -u Anonymizer --password-stdin
          docker build . -t ghcr.io/balajeeaddanki/anonymizer:latest -f DockerFile
          docker push ghcr.io/balajeeaddanki/anonymizer:latest